/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import model.Jegyzet;

/**
 *
 * @author g
 */
public class JegyzetForm extends javax.swing.JFrame {

    private HashMap<String, ArrayList<Jegyzet>> betoltottJegyzetek;
    public JegyzetForm() {
        initComponents();
    }

    public JegyzetForm(HashMap<String, ArrayList<Jegyzet>> jegyzeteim) {
        this();
        betoltottJegyzetek = jegyzeteim;
        cBfeltolt();
        jLfeltolt(hashMapCB.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jegyzetPanel = new javax.swing.JPanel();
        hashMapCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jegyzetJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jegyzetContent = new javax.swing.JTextPane();
        ujJegyzetPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jegyzetJList);

        jegyzetContent.setToolTipText("");
        jScrollPane2.setViewportView(jegyzetContent);

        javax.swing.GroupLayout jegyzetPanelLayout = new javax.swing.GroupLayout(jegyzetPanel);
        jegyzetPanel.setLayout(jegyzetPanelLayout);
        jegyzetPanelLayout.setHorizontalGroup(
            jegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jegyzetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(hashMapCB, 0, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jegyzetPanelLayout.setVerticalGroup(
            jegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jegyzetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hashMapCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jegyzetek", jegyzetPanel);

        javax.swing.GroupLayout ujJegyzetPanelLayout = new javax.swing.GroupLayout(ujJegyzetPanel);
        ujJegyzetPanel.setLayout(ujJegyzetPanelLayout);
        ujJegyzetPanelLayout.setHorizontalGroup(
            ujJegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        ujJegyzetPanelLayout.setVerticalGroup(
            ujJegyzetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Új", ujJegyzetPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Új");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JegyzetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JegyzetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JegyzetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JegyzetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JegyzetForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hashMapCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jegyzetContent;
    private javax.swing.JList<String> jegyzetJList;
    private javax.swing.JPanel jegyzetPanel;
    private javax.swing.JPanel ujJegyzetPanel;
    // End of variables declaration//GEN-END:variables

    private void cBfeltolt() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for (Map.Entry<String, ArrayList<Jegyzet>> entry : betoltottJegyzetek.entrySet()) {
            Object key = entry.getKey();
            dcbm.addElement(key);
        }
        hashMapCB.setModel(dcbm);
    }

    private void jLfeltolt(String key) {
        DefaultListModel dlm = new DefaultListModel();
        ArrayList<Jegyzet> jegyzetek = betoltottJegyzetek.get(key);
        for (Jegyzet jegyzet : jegyzetek) {
            dlm.addElement(jegyzet.getNev());
        }
        jegyzetJList.setModel(dlm);
    }
}
